this.state = {
    personalInfo: {
      section: "personalInfo",
      id: nanoid(),
      firstName: "",
      lastName: "",
      title: "",
      email: "",
      phone: "",
      address: "",
      description: "",
      handleChange: this.handleChange,
    },
    experience: {
      section: "experience",
      id: nanoid(),
      position: "",
      company: "",
      city: "",
      from: "",
      to: "",
      handleChange: this.handleChange,
    },
    education: {
      section: "education",
      id: nanoid(),
      university: "",
      city: "",
      degree: "",
      subject: "",
      from: "",
      to: "",
      handleChange: this.handleChange,
    },